include: package:flutter_lints/flutter.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  exclude:
    - "lib/ffi/**"
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    implicit_dynamic_parameter: warning
    invalid_annotation_target: ignore
    