name: aqua
description: Aqua

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  sqflite: ^2.0.0+4
  path: ^1.8.0
  flutter_lints: ^2.0.1
  intl: ^0.17.0
  flutter_riverpod: ^0.14.0+3
  path_drawing: ^1.0.0
  flutter_svg: ^1.1.3
  flutter_screenutil: ^5.0.0+2
  google_fonts: ^2.1.0
  logger: ^1.1.0
  isolator: ^1.0.1
  rxdart: ^0.27.2
  json_serializable: ^6.3.1
  json_annotation: ^4.6.0
  freezed_annotation: ^2.1.0
  nanoid: ^1.0.0
  tuple: ^2.0.0
  mobile_scanner: ^3.0.0-beta.1
  qr_flutter: ^4.0.0
  # plus
  share_plus: ^2.1.4
  device_info_plus: ^2.1.0
  package_info_plus: ^1.0.6
  url_launcher: ^6.0.15
  # app icon
  flutter_launcher_icons: ^0.9.2
  decimal: ^1.3.0
  path_provider: ^2.0.5
  web_socket_channel: ^2.1.0
  flare_flutter: ^3.0.2
  in_app_review: ^2.0.3
  flutter_inappwebview: ^5.3.2
  image_picker: ^0.8.5+3
  jovial_svg: ^1.1.6
  jovial_misc: ^0.8.4

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
  uni_links: ^0.5.1
  flutter_font_icons: ^2.2.5
  youtube_player_flutter: ^8.1.0
  connectivity_plus: ^2.3.5
  flutter_keyboard_visibility: ^5.3.0
  confetti: ^0.7.0
  ffi: ^1.0.0
  async: ^2.8.2
  http: ^0.13.4
  collection: ^1.16.0
  webview_flutter: ^3.0.4

dev_dependencies:
  ffigen: ^4.0.0
  build_runner: ^2.1.2
  freezed: ^2.1.0+1
  analyzer: ^4.2.0
  flutter_test:
    sdk: flutter

dependency_overrides:
  freezed_annotation:

flutter_icons:
  ios: true
  image_path: "assets/icon/icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  generate: true
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/arrow_backup.svg
    - assets/aqua_logo_noshadow.svg
    - assets/aqua_logo.svg
    - assets/backup_wallet.svg
    - assets/failure.svg
    - assets/logo.svg
    - assets/passcode.svg
    - assets/touch.svg
    - assets/face_id.svg
    - assets/wallet_safety.svg
    - assets/recovery_phrase.svg
    - assets/tab_wallet.svg
    - assets/tab_exchange.svg
    - assets/tab_profile.svg
    - assets/wallet_receive.svg
    - assets/wallet_send.svg
    - assets/wallet_scan.svg
    - assets/send_scan.svg
    - assets/send_paste.svg
    - assets/search.svg
    - assets/qr.svg
    - assets/copy.svg
    - assets/set_amount.svg
    - assets/share.svg
    - assets/send_summary.svg
    - assets/swap.svg
    - assets/liquid_card.svg
    - assets/profile_support.svg
    - assets/profile_phrase.svg
    - assets/profile_settings.svg
    - assets/profile_terms.svg
    - assets/profile_about.svg
    - assets/external_link.svg
    - assets/buy_bitcoin.svg
    - assets/buy_liquid_bitcoin.svg
    - assets/pending.svg
    - assets/incoming.svg
    - assets/outgoing.svg
    - assets/exchange.svg
    - assets/marketplace.svg
    - assets/nft.svg
    - assets/marketplace/bitfinex.svg
    - assets/marketplace/btse.png
    - assets/marketplace/sideshift.svg
    - assets/sideshift_full.svg
    - assets/marketplace/sideswap.svg
    - assets/marketplace/swan.svg
    - assets/exchange_swap.svg
    - assets/bitcoin_placeholder.svg
    - assets/swap_background.svg
    - assets/swap_logo.svg
    - assets/welcome_logo.svg
    - assets/wordlist.txt
    - assets/animations/mellow.flr
    - assets/animations/create_wallet.flr
    - assets/asset_icons/asset_unknown.svg
    - assets/asset_icons/BTC.svg
    - assets/asset_icons/BTSE.svg
    - assets/asset_icons/LCAD.svg
    - assets/asset_icons/USDt.svg
    - assets/asset_icons/LBTC.svg
    - assets/asset_icons/EURx.svg
    - assets/wallet_import.svg
    - assets/wallet_create.svg
    - assets/album.svg
    - assets/history.svg
    - assets/success_treasure.svg
    - assets/marketplace_swap.svg
    - assets/marketplace_buy.svg
    - assets/marketplace_exchange.svg
    - assets/pokerchip.svg

ffigen:
  output: "lib/ffi/generated_bindings.dart"
  headers:
    entry-points:
      - "crypto/gdk-android-jni/include/gdk/gdk.h"
      - "crypto/gdk-android-jni/include/gdk/libwally-core/wally_bip39.h"
  typedefs:
    include:
      - ".*"
  functions:
    expose-typedefs:
      include:
        - ".*" # Do this to expose types for all function.
  symbol-address:
    include:
      - ".*" # Do this to expose all function pointers.
  structs:
    exclude:
      - "(.*)sigaction(.*)"
  unions:
    exclude:
      - "(.*)sigaction(.*)"
  llvm-path:
    - "/opt/local/libexec/llvm-10"
    - "/Library/Developer/CommandLineTools/usr"
